- name: Setup Web Server and Deploy HTML Files
  hosts: webservers
  become: true
  tasks:

    - name: Install Apache Web Server
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Start Apache using service command
      shell: |
        service apache2 restart
      args:
        executable: /bin/bash

    - name: Copy index.html to vm1
      copy:
        src: index1.html
        dest: /var/www/html/index.html
      when: inventory_hostname == "vm1"

    - name: Copy index.html to vm2
      copy:
        src: index2.html
        dest: /var/www/html/index.html
      when: inventory_hostname == "vm2"
